import React,{useEffect,useState} from 'react';
import {BarChart3,Table2,Search} from 'lucide-react';
import {loadData,format} from './data';

function Plot({points,label,unit}){
 const values=points.filter(p=>p[1]!=null);if(!values.length)return <p className="empty">No numeric observations in this selection.</p>;
 const w=760,h=320,l=85,r=25,t=25,b=65;const lo=Math.min(0,...values.map(p=>p[1])),hi=Math.max(0,...values.map(p=>p[1]));const span=hi-lo||1;
 const x=i=>l+(i+.5)*(w-l-r)/points.length,y=v=>h-b-(v-lo)/span*(h-t-b),step=Math.max(1,Math.ceil(points.length/7));
 return <><p className="chart-unit">{unit}</p><svg className="source-chart" viewBox={`0 0 ${w} ${h}`} role="img" aria-label={`${label}: ${points.length} observations`}>
 {[0,.25,.5,.75,1].map(f=><g key={f}><line x1={l} x2={w-r} y1={y(lo+f*span)} y2={y(lo+f*span)} className="grid-line"/><text x={l-9} y={y(lo+f*span)+4} textAnchor="end">{format(lo+f*span,1)}</text></g>)}
 {points.map((p,i)=><g key={i}>{p[1]!=null&&<rect tabIndex={0} x={x(i)-Math.min(28,(w-l-r)/points.length*.65)/2} width={Math.min(28,(w-l-r)/points.length*.65)} y={Math.min(y(0),y(p[1]))} height={Math.max(1,Math.abs(y(p[1])-y(0)))} fill="#087f83"><title>{p[0]}: {format(p[1])} {unit}{p[2]&&p[2]!=='not_specified'?' · '+p[2]:''}</title></rect>}{(i%step===0||i===points.length-1)&&<text x={x(i)} y={h-b+22} textAnchor="middle">{String(p[0]).length>18?String(p[0]).slice(0,16)+'…':p[0]}</text>}</g>)}
 </svg><p className="chart-note">Hover or focus a bar for the exact value. Missing observations remain blank. The chart does not aggregate or rescale the source values.</p></>;
}
export function SourceChart({source,preview}){
 const[data,setData]=useState(null),[error,setError]=useState(''),[q,setQ]=useState(''),[chosen,setChosen]=useState(0),[tab,setTab]=useState('chart');
 const[sheet,setSheet]=useState(0),[column,setColumn]=useState(1),[header,setHeader]=useState(0);
 useEffect(()=>{let active=true;if(source.chart_file)loadData(source.chart_file).then(d=>active&&setData(d)).catch(e=>active&&setError(e.message));else setData({series:[],reason:'Choose a source column to inspect this table.'});return()=>{active=false}},[source.source_id]);
 if(error)return <p role="alert">{error}</p>;if(!data)return <p role="status">Loading chart and definitions…</p>;
 const series=data.series||[],s=series[chosen]||series[0];const sheets=data.sheets||[{name:preview?.sheet||'Source table',rows:preview?.rows||[]}];const rows=sheets[sheet]?.rows||[];const headers=rows[header]||[];
 const points=s?s.points:rows.slice(header+1).map((r,i)=>{const raw=String(r[column]??'').trim();const value=raw!==''&&/^[-+]?\d+(?:\.\d+)?$/.test(raw)?Number(raw):null;return [r[0]||`Row ${header+i+2}`,value,'source value']}).filter(p=>p[1]!=null);
 const label=s?.label||headers[column]||`Column ${column+1}`,unit=s?.unit||'Source units — see original column labels';
 return <section className="panel source-explorer"><div className="panel-heading"><div><h2>Explore this dataset</h2><p>All geographic areas and source breakdowns are available here.</p></div></div>
 {series.length>0?<div className="source-series-controls"><label>Find a series<input aria-label="Find a series" value={q} onChange={e=>setQ(e.target.value)} placeholder="Search a measure, region or category…"/></label><label>Indicator / series<select aria-label="Indicator / series" value={chosen} onChange={e=>setChosen(Number(e.target.value))}>{series.map((s,i)=>({s,i})).filter(({s,i})=>i===chosen||s.label.toLowerCase().includes(q.toLowerCase())).map(({s,i})=><option value={i} key={i}>{s.label}</option>)}</select></label></div>:<><p className="notice">{data.reason}</p><div className="source-series-controls"><label>Sheet<select aria-label="Chart sheet" value={sheet} onChange={e=>{setSheet(Number(e.target.value));setHeader(0);setColumn(1)}}>{sheets.map((s,i)=><option value={i} key={i}>{s.name}</option>)}</select></label><label>Column-label row<select aria-label="Column-label row" value={header} onChange={e=>setHeader(Number(e.target.value))}>{rows.slice(0,30).map((r,i)=><option value={i} key={i}>Row {i+1}: {r.filter(Boolean).join(' · ').slice(0,120)}</option>)}</select></label><label>Value column<select aria-label="Value column" value={column} onChange={e=>setColumn(Number(e.target.value))}>{Array.from({length:Math.max(0,...rows.map(r=>r.length))},(_,i)=><option value={i} key={i}>{i+1}: {headers[i]||'Unlabelled column'}</option>)}</select></label></div><p className="chart-note">Choose one measure with consistent units. This is a source-column comparison, not an inferred time series. Text and missing cells are excluded; numeric values are unchanged.</p></>}
 <div className="dataset-view-tabs"><button className={tab==='chart'?'active':''} onClick={()=>setTab('chart')}><BarChart3 size={16}/>Chart</button><button className={tab==='table'?'active':''} onClick={()=>setTab('table')}><Table2 size={16}/>Data table</button></div>
 <h3>{label}</h3>{tab==='chart'?<Plot points={points} label={label} unit={unit}/>:<div className="table-scroll"><table><thead><tr><th>Period / category</th><th>Value</th><th>Status</th></tr></thead><tbody>{points.map((p,i)=><tr key={i}><th>{p[0]}</th><td>{format(p[1])}</td><td>{p[1]==null?'Missing':p[2]==='not_specified'?'Reported':p[2]}</td></tr>)}</tbody></table></div>}
 <div className="source-definition"><h3>Dataset details & definition</h3><dl><dt>Original NSO title</dt><dd>{source.title}</dd><dt>Selected indicator / breakdown</dt><dd>{label}</dd><dt>Unit</dt><dd>{unit}</dd><dt>Coverage</dt><dd>National, regional, provincial or other categories exactly as labelled by NSO. No geography filter is applied.</dd><dt>Reference periods</dt><dd>{s?`${points[0]?.[0]} – ${points.at(-1)?.[0]}`:'As labelled in the source sheet'}</dd><dt>Publisher</dt><dd>Vietnam National Statistics Office</dd></dl>{data.notes?.map((n,i)=><p key={i}>{n}</p>)}<p>Definitions and units come from the source labels and supplied metadata. A separate methodological definition is not supplied for every table; consult the original NSO source for additional notes. Preliminary and estimated labels are retained, and missing values are not zero.</p></div></section>;
}
