import React,{useEffect,useState} from 'react';
import {ChevronRight,ArrowUpRight,Search,ChevronDown} from 'lucide-react';
import {loadData,format} from './data';
export const SUBJECT_GROUPS=[
 ['people','Population and employment',[['population','Population'],['employment','Employment']]],
 ['accounts','National accounts and finance',[['national_account','National accounts'],['banking_insurance_budget','Banking, insurance and State budget']]],
 ['economy','Economy',[['agriculture','Agriculture, Forestry and Fishery'],['investment','Investment and Construction'],['industry','Industry'],['enterprises','Enterprises'],['trade_services','Trade and Tourism'],['prices','Prices']]],
 ['society','Society, environment and territory',[['education','Science and technology, education'],['health_culture_environment','Health, Culture, Sport, Living standards, Social order, Safety and Environment'],['administration_land_climate','Administrative unit, Land and Climate']]],
];
export const RELEASES=[['monthly-report','Socio-economic monthly report'],['cpi','CPI, gold and USD price indexes'],['iip','Index of Industrial Production'],['import-export','Preliminary Exports and Imports']];
const topics=SUBJECT_GROUPS.flatMap(g=>g[2]);
export const topicLabel=id=>topics.find(t=>t[0]===id)?.[1]||RELEASES.find(t=>t[0]===id)?.[1]||id;
export function StatisticsCatalogue({params}){
 const[data,setData]=useState(null),[releases,setReleases]=useState(null),[error,setError]=useState('');
 const[q,setQ]=useState(params.get('q')||''),[topic,setTopic]=useState(params.get('topic')||'all'),[group,setGroup]=useState(params.get('group')||''),[page,setPage]=useState(1);
 useEffect(()=>{loadData('full-catalogue.json').then(setData).catch(e=>setError(e.message));loadData('release-catalogue.json').then(setReleases).catch(()=>{})},[]);
 useEffect(()=>{setQ(params.get('q')||'');setTopic(params.get('topic')||'all');setGroup(params.get('group')||'')},[params.toString()]);
 useEffect(()=>setPage(1),[q,topic,group]);
 if(!data)return <main className="wrap page" role={error?'alert':'status'}>{error||'Loading statistics…'}</main>;
 const allowed=new Set(topics.map(t=>t[0])),sources=data.sources.filter(s=>allowed.has(s.section));
 const isRelease=RELEASES.some(t=>t[0]===topic),groupTopics=SUBJECT_GROUPS.find(g=>g[0]===group)?.[2].map(t=>t[0]);
 const collection=isRelease?(releases?.items||[]).filter(s=>s.archive===topic):sources.filter(s=>(topic==='all'||s.section===topic)&&(!groupTopics||groupTopics.includes(s.section)));
 const filtered=collection.filter(s=>(s.title+' '+(s.source_id||'')).toLowerCase().includes(q.toLowerCase()));
 const select=(id,g='')=>{setTopic(id);setGroup(g)};const size=25,pages=Math.max(1,Math.ceil(filtered.length/size));
 return <main className="wrap page"><div className="breadcrumb"><a href="#/">Home</a><ChevronRight size={14}/>Statistics</div><p className="eyebrow">EXPLORE THE DATA</p><h1>Statistics by topic</h1><p className="intro">Explore NSO statistics, chart the source series and download complete datasets.</p>
 <div className="statistics-shortcuts">{SUBJECT_GROUPS.map(([id,label])=><a className={group===id?'selected':''} key={id} href={'#/statistics?group='+id}>{label}<ChevronRight size={17}/></a>)}{RELEASES.map(([id,label])=><a key={id} href={releases?.enabled?'#/statistics?topic='+id:'https://www.nso.gov.vn/en/'+id+'/'} {...(!releases?.enabled?{target:'_blank',rel:'noreferrer'}:{})}>{label}{releases?.enabled?<ChevronRight size={17}/>:<ArrowUpRight size={17}/>}</a>)}</div>
 <div className="catalogue-layout"><aside className="topic-sidebar grouped-topics"><h3>Browse statistics</h3><button className={topic==='all'&&!group?'selected':''} onClick={()=>select('all')}>All topics<span>{sources.length}</span></button>{SUBJECT_GROUPS.map(([id,label,children])=><details key={id} open={group===id||children.some(t=>t[0]===topic)||undefined}><summary>{label}<ChevronDown size={15}/></summary><button onClick={()=>select('all',id)} className={group===id?'selected':''}>All in this group</button>{children.map(([tid,title])=><button key={tid} onClick={()=>select(tid)} className={topic===tid?'selected':''}>{title}<span>{sources.filter(s=>s.section===tid).length}</span></button>)}</details>)}{releases?.enabled&&<div className="release-menu"><h3>Statistical releases</h3>{RELEASES.map(([id,label])=><button key={id} className={topic===id?'selected':''} onClick={()=>select(id)}>{label}<span>{releases.items.filter(s=>s.archive===id).length}</span></button>)}</div>}</aside>
 <section className="compact-catalogue"><div className="catalogue-search"><Search size={19}/><input aria-label="Search datasets" value={q} onChange={e=>setQ(e.target.value)} placeholder="Search original NSO titles or table IDs…"/></div><div className="catalogue-toolbar"><p role="status">{format(filtered.length,0)} {isRelease?'releases':'datasets'}{topic!=='all'?' · '+topicLabel(topic):group?' · '+SUBJECT_GROUPS.find(g=>g[0]===group)?.[1]:''}</p><span>{size} per page</span></div>{isRelease&&<p className="chart-note">Last five years by issue date. Spreadsheet downloads are provided where NSO supplies them; PDF-only and narrative releases link to the official page.</p>}
 <div className="compact-dataset-list">{filtered.slice((page-1)*size,page*size).map(s=><a className="compact-dataset-row" key={s.source_id||s.id} href={isRelease?'#/release/'+s.id:'#/dataset/'+s.source_id}><div><h3>{s.title}</h3><p>{isRelease?s.date:[s.source_id,s.periods?.length?s.periods[0]+'–'+s.periods.at(-1):'',s.chart_series?`${s.chart_series} series`:'Source table'].filter(Boolean).join(' · ')}</p></div><ChevronRight size={18}/></a>)}</div>{!filtered.length&&<p className="empty">No datasets match your search.</p>}<div className="pagination"><button className="button secondary" disabled={page<=1} onClick={()=>setPage(page-1)}>Previous</button><span>Page {page} of {pages}</span><button className="button secondary" disabled={page>=pages} onClick={()=>setPage(page+1)}>Next</button></div></section></div></main>;
}
